# Generated by Django 4.0.4 on 2022-05-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='No_of_units',
        ),
        migrations.AddField(
            model_name='stock',
            name='ProductId',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
